### ISSUE TITLE
Fail to unzip dataset 

### ISSUE THREAD

**Issue by wntg** [xieyuankun/Codecfake#3]
When I download dataset and confirm md5,I still unzip this files.

Archive:  dev_split.z01                                                                                                    
  End-of-central-directory signature not found.  Either this file is not                                             
  a zipfile, or it constitutes one disk of a multi-part archive.  In the                                          
  latter case the central directory and zipfile comment will be found on                                    
  the last disk(s) of this archive.                                                                                 
unzip:  cannot find zipfile directory in one of dev_split.z01 or                                            
        dev_split.z01.zip, and cannot find dev_split.z01.ZIP, period.

**Comment by wntg** [comment]
Only the label file is successfully.

**Comment by xieyuankun** [comment]
A relatively stable method is as follows: if you need to unzip dev, you should download dev_split.zip, dev_split.z01, and dev_split.z02 into the same folder. Then, merge them into a complete dev.zip by running `zip -F dev_split.zip --out dev.zip` After that, unzip the complete package with `unzip dev.zip`
