### ISSUE TITLE
Confusion with other codecfake paper

### ISSUE THREAD

**Issue by tcourat** [xieyuankun/Codecfake#4]
Hi,

I am a bit confused. Is there any link between your work and the work of this paper : https://codecfake.github.io/  . Same dataset name. Similar choice of experiments . Or is this a totally separate work with a totally different dataset ?

Also it seems that you re-submitted another paper https://arxiv.org/abs/2406.08112 with fewer pages. It seems that there is no new content. Am I right ?

Thanks

**Comment by xieyuankun** [comment]
Hello, thank you for your interest in this work. The link: https://codecfake.github.io/ is align with the paper: https://arxiv.org/abs/2406.07237. This work, along with ours, has been accepted by Interspeech 2024. Although the names are very similar, they are actually quite different in terms of data construction, countermeasure, and testing condition. In fact, there is a slight difference in the names as well; we are Codecfake, and they are CodecFake.

Here are our current works related to Codecfake:
Conference version: Accepted by Interspeech 2024: https://arxiv.org/abs/2406.08112
Journal revision version: https://arxiv.org/abs/2405.04880
Code: https://github.com/xieyuankun/Codecfake
Dataset: https://zenodo.org/records/11171708
