### ISSUE TITLE
文件找不到

### ISSUE THREAD

**Issue by Judy19811** [xieyuankun/Codecfake#5]
config = Wav2Vec2Config.from_json_file("/data3/xyk/huggingface/wav2vec2-xls-r-300m/config.json")
    processor = Wav2Vec2FeatureExtractor.from_pretrained("/data3/xyk/huggingface/wav2vec2-xls-r-300m/")
    model = Wav2Vec2Model.from_pretrained("/data3/xyk/huggingface/wav2vec2-xls-r-300m/").cuda()这三个路径的文件好像没有呢

**Comment by xieyuankun** [comment]
您好，该预训练模型位于https://huggingface.co/facebook/wav2vec2-xls-r-300m/tree/main
请将该库中的文件下载至一个文件夹，比如我的是放在/data3/xyk/huggingface/ ，下载后即可调通。

另外的方法是写成huggingface直读路径，此三行换成
`processor =  Wav2Vec2FeatureExtractor.from_pretrained("facebook/wav2vec2-xls-r-300m")
model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-xls-r-300m").cuda()
config = Wav2Vec2Config.from_json_file("facebook/wav2vec2-xls-r-300m")`
但在国内需要加`export HF_ENDPOINT=https://hf-mirror.com` 在preprocess.py最上端，走镜像口。

**Comment by Judy19811** [comment]
助教已收到
