### ISSUE TITLE
real audio samples in A3

### ISSUE THREAD

**Issue by RedamancyAY** [xieyuankun/Codecfake#8]
Hello, can you share the 49,274 real audio samples in A3?

**Comment by xieyuankun** [comment]
Hello, due to copyright issues, we cannot directly provide the real audio. You can obtain the YouTube link of A3 real audio from the following URL and download it by yourself: https://github.com/cdjkim/audiocaps/blob/master/dataset/train.csv.

**Comment by rosezc** [comment]
没有找到[https:](https://github.com/cdjkim/audiocaps/blob/master/dataset/train.csv) //github.com/cdjkim/audiocaps/blob/master/dataset/train.csv中的A3的real的音频文件，请问可以再分享一下吗？
